### ISSUE TITLE
Logger settings are being overwritten in base_settings.py

### ISSUE THREAD

**Issue by SarthakSingh31** [uw-it-aca/django-container#35]
https://github.com/uw-it-aca/django-container/blob/develop/project/base_settings.py#L128

Both elements of the dict have the same key so the latter one is overwriting the first. This will make all the logs only report errors by default.

**Comment by ezturner** [comment]
This should be fixed by https://github.com/uw-it-aca/django-container/pull/37

**Comment by SarthakSingh31** [comment]
Fixed by #38
